name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pdm from PyPI
        uses: install-pinned/pdm@8a1964a4d70aa07d5bef56db7f0fc3af76591887
      - run: pdm sync --dev --no-self
      - run: pdm run fmt
      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
